### ISSUE TITLE
Install can't find typings

### ISSUE THREAD

**Issue by churchilllake** [zaggino/brackets-typescript#1]
Getting this output during install on Mac, i think due to typings not being accessible.  typings is installed and a link exists to it in /usr/local/bin.

```
using node v0.10.24, npm 2.14.5

node in path version v0.10.24, npm in path version 2.14.5

loading npm

executing npm install /Users/robbin/Library/Application Support/Brackets/extensions/user brackets-typescript

sh: typings: command not found

npm

WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.24","npm":"2.14.5"})

npm
 WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.24","npm":"2.14.5"})

{ cause: 
   { [Error: brackets-inspection-gutters@0.2.4 postinstall: `typings install`
   spawn ENOENT]
     code: 'ELIFECYCLE',
     errno: 'ENOENT',
     syscall: 'spawn',
     file: 'sh',
     pkgid: 'brackets-inspection-gutters@0.2.4',
     stage: 'postinstall',
     script: 'typings install',
     pkgname: 'brackets-inspection-gutters' },
  isOperational: true,
  code: 'ELIFECYCLE',
  errno: 'ENOENT',
  syscall: 'spawn',
  file: 'sh',
  pkgid: 'brackets-inspection-gutters@0.2.4',
  stage: 'postinstall',
  script: 'typings install',
  pkgname: 'brackets-inspection-gutters' }

Unhandled rejection Error: brackets-inspection-gutters@0.2.4 postinstall: `typings install`
spawn ENOENT
    at ChildProcess.<anonymous> (/Users/robbin/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/npm/lib/utils/spawn.js:17:16)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)


> brackets-inspection-gutters@0.2.4 postinstall /Users/robbin/Library/Application Support/Brackets/extensions/user/node_modules/brackets-typescript/node_modules/brackets-inspection-gutters
> typings install

```

**Comment by zaggino** [comment]
@churchilllake please try again, I've fixed the brackets-inspection-gutters dependency

**Comment by churchilllake** [comment]
It worked like a charm
